config/routes.rb
Prairie::Application.routes.draw do

  root :to => 'pages#welcome'

  match "welcome" => "pages#welcome"
  get "login", :to => "sessions#new", as: "login"
  get "logout", :to => "sessions#destroy", as: "logout"
  resources :sessions, :only => [:new, :create]

  get "register", :to => "users#new", as: "register"
  resources :users, except: :show

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password, :password_confirmation
  has_secure_password

  validates_format_of :email, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, :uniqueness => true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def current_user
    current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def welcome
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to welcome_url, notice: "Login successful"
    else
      flash.now.alert = "Email or password invalid"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to users_path, notice: 'User was successfully created.'
    else
      render "new" 
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      redirect_to @user, notice: 'User was successfully updated.'
    else
        render action: "edit"
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
      redirect_to users_url
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Prairie</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <% if current_user %>
    <p>Howdy, <%= current_user.email %>  | <%= link_to "Sign out", logout_path %></p>
  <% else %>
    <p><%= link_to "Login or create account", login_path  %></p>
  <% end %>


<%= yield %>

</body>
</html>

app/views/pages/welcome.html.erb
Welcome to Prairie.

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2>Please correct the following <%= pluralize(@user.errors.count, "error") %> errors:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>
    <legend>User admin</legend>
        <div class="field">
          <%= f.label :email %><br>
          <%= f.text_field :email %>
        </div>

        <div class="field">
          <%= f.label :password %><br>
          <%= f.password_field :password %>
        </div>

        <div class="field">
          <%= f.label :password_confirmation %><br>
          <%= f.password_field :password_confirmation %>
        </div>

        <div class="actions">
          <%= f.submit "Submit" %>
        </div>
      <%= link_to "Already have an account?", login_path %>
  </fieldset>
<% end %>

app/views/users/edit.html.erb
<h1>Edit your admin account</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Email</th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.email %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>Create your new admin account</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>